# Generated by Django 5.2.3 on 2025-06-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_task_id',
            field=models.IntegerField(default=0),
        ),
    ]
